MD_CORE_MODEL = {
    'typename': 'pycsw:CoreMetadata',
    'outputschema': 'http://pycsw.org/metadata',
    'mappings': {
        # Needed for PYCSW
        'pycsw:Identifier': 'identifier',
        'pycsw:Typename': 'typename',
        'pycsw:Schema': 'schema',
        'pycsw:MdSource': 'mdsource',
        'pycsw:InsertDate': 'insert_date_utc',
        'pycsw:XML': 'xml',
        'pycsw:AnyText': 'anytext',
        'pycsw:BoundingBox': 'wkt_geometry',
        'pycsw:Links': 'links',
        'pycsw:Keywords': 'keywords',
        'pycsw:Type': 'type',
        'pycsw:Title': 'product_name',
        'pycsw:Abstract': 'description',
        'pycsw:AlternateTitle': 'product_name',
        'pycsw:AccessConstraints': 'classification',
        'pycsw:Creator': 'producer_name',
        'pycsw:CRS': 'srs_id',
        'pycsw:Publisher': 'producer_name',
        'pycsw:Contributor': 'producer_name',
        'pycsw:CreationDate': 'creation_date_utc',
        'pycsw:Date': 'creation_date_utc',
        'pycsw:Format': 'type',
        'pycsw:Modified': 'update_date_utc',
        'pycsw:Source': 'product_name',
        'pycsw:Relation': '',
        'pycsw:Language': '',
        'pycsw:TopicCategory': '',

        # Common profile fields
        'pycsw:Classification': 'classification',
        'pycsw:ProductId': 'product_id',
        'pycsw:ProductVersion': 'product_version',
        'pycsw:ProductType': 'product_type',
        'pycsw:productSubType': 'product_sub_type',
        'pycsw:CRSName': 'srs_name',
        'pycsw:updateDateUTC': 'update_date_utc',
        'pycsw:ingestionDateUTC': 'ingestion_date_utc',
        'pycsw:TempExtent_begin': 'acquisition_time_begin_utc',
        'pycsw:TempExtent_end': 'acquisition_time_end_utc',
        'pycsw:maxResolutionDegree': 'max_resolution_degree',
        'pycsw:minResolutionDegree': 'min_resolution_degree',
        'pycsw:maxResolutionMeter': 'max_resolution_meter',
        'pycsw:minResolutionMeter': 'min_resolution_meter',
        'pycsw:maxHorizontalAccuracyCEP90': 'max_horizontal_accuracy_cep_90',
        'pycsw:minHorizontalAccuracyCEP90': 'min_horizontal_accuracy_cep_90',
        'pycsw:maxAbsoluteAccuracyLEP90': 'max_absolute_accuracy_lep_90',
        'pycsw:minAbsoluteAccuracyLEP90': 'min_absolute_accuracy_lep_90',
        'pycsw:maxRelativeAccuracyLEP90': 'max_relative_accuracy_lep_90',
        'pycsw:minRelativeAccuracyLEP90': 'min_relative_accuracy_lep_90',
        'pycsw:sensorType': 'sensors',
        'pycsw:region': 'region',
        'pycsw:footprint': 'footprint_geojson',
        'pycsw:noDataValue': 'no_data_value',
        'pycsw:areaOrPoint': 'area_or_point',
        'pycsw:dataType': 'data_type',
        'pycsw:verticalType': 'vertical_type',
        'pycsw:verticalSrsId': 'vertical_srs_id',
        'pycsw:verticalSrsName': 'vertical_srs_name',

        'pycsw:productBBox':'product_bbox',
        'pycsw:productStatus': 'product_status',
    }
}
