# =================================================================
#
# Authors: Ricardo Garcia Silva <ricardo.garcia.silva@gmail.com>
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2017 Ricardo Garcia Silva
# Copyright (c) 2025 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================
#
#
# This docker compose file demos how to use the pycsw docker image with a
# PostgreSQL/PostGIS database.
#
# docker compose usage:
#
# docker compose up
#
# docker stack (in a docker swarm):
#
# PYCSW_DOCKER_IMAGE=2.1-dev docker stack deploy --compose-file docker-compose.yml pycsw
#

services:
  solr:
    container_name: solr
    image: solr:slim
    volumes:
      - solr-data:/var/solr
    ports:
      - 8983:8983
    networks:
      - pycsw-net
    command:
      - solr-precreate
      - gettingstarted
  pycsw:
    container_name: pycsw
    depends_on:
      - solr
    build: ../../..
    environment:
        PYCSW_SERVER_URL: http://localhost:8000
    ports:
      - 8000:8000
    volumes:
      - ./pycsw-solr.yml:/etc/pycsw/pycsw.yml
      - ./solr_helper.py:/usr/local/lib/python3.10/site-packages/pycsw/pycsw/plugins/repository/solr_helper.py
      - ./solr_pycsw.py:/usr/local/lib/python3.10/site-packages/pycsw/pycsw/plugins/repository/solr_pycsw.py
    networks:
      - pycsw-net

networks:
  pycsw-net:

volumes:
  solr-data:
