apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: pycsw
  name: pycsw
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30000
  selector:
    io.kompose.service: pycsw
status:
  loadBalancer: {}
