global:
  namespace: default

db:
  name: db
  image: postgis/postgis:12-3.1
  port: 5432
  database: pycsw
  user: postgres
  pass: mypass
  volume_name: db-data
  volume_path: /var/lib/postgresql/data/pgdata
  volume_size: 500Mi
  volume_access_modes: ReadWriteOnce
  volume_storage_type: standard

pycsw:
  name: pycsw
  image: geopython/pycsw:latest
  container_port: 8000
  service_type: NodePort
  service_port: 8000
  service_port_name: http
  service_node_port: 30000
  # service_port_protocol: TCP
  # service_target_port: 8000
  configmap_name: pycsw-configmap
  volume_name: pycsw-config
  volume_path: /etc/pycsw
  config:
    server:
      home: /home/pycsw
      url: http://localhost:8000
      mimetype: application/xml; charset=UTF-8
      encoding: UTF-8
      language: en-US
      maxrecords: 10
      loglevel: DEBUG
      logfile: " "
      # ogc_schemas_base: http://foo
      # federatedcatalogues: http://catalog.data.gov/csw
      # pretty_print: true
      # gzip_compresslevel: 8
      # domainquerytype: range
      # domaincounts: true
      # spatial_ranking: true
      profiles: apiso
      # workers: 2
      timeout: 30
    manager:
      transactions: "false"
      allowed_ips: 127.0.0.1
      # csw_harvest_pagesize: 10
    metadata:
      identification_title: pycsw Geospatial Catalogue
      identification_abstract: pycsw is an OARec and OGC CSW server implementation written in Python
      identification_keywords: catalogue,discovery,metadata
      identification_keywords_type: theme
      identification_fees: None
      identification_accessconstraints: None
      provider_name: Organization Name
      provider_url: https://pycsw.org/
      contact_name: Lastname, Firstname
      contact_position: Position Title
      contact_address: Mailing Address
      contact_city: City
      contact_stateorprovince: Administrative Area
      contact_postalcode: Zip or Postal Code
      contact_country: Country
      contact_phone: +xx-xxx-xxx-xxxx
      contact_fax: +xx-xxx-xxx-xxxx
      contact_email: Email Address
      contact_url: Contact URL
      contact_hours: Hours of Service
      contact_instructions: During hours of service.  Off on weekends.
      contact_role: pointOfContact
    repository:
      database: postgresql://postgres:mypass@db/pycsw
      table: records
      # mappings: path/to/mappings.py
      # filter: type = 'http://purl.org/dc/dcmitype/Dataset'
    inspire:
      enabled: "true"
      languages_supported: eng,gre
      default_language: eng
      date: YYYY-MM-DD
      gemet_keywords: Utility and governmental services
      conformity_service: notEvaluated
      contact_name: Organization Name
      contact_email: Email Address
      temp_extent: YYYY-MM-DD/YYYY-MM-DD
    
