**2013-06-07** - `pycsw 1.4.2 released <http://lists.osgeo.org/pipermail/pycsw-devel/2013-June/000206.html>`_

**2013-04-12** - `pycsw enters OSGeo Incubation <http://lists.osgeo.org/pipermail/pycsw-devel/2013-April/000180.html>`_

**2013-03-26** - `pycsw 1.4.1 released <http://lists.osgeo.org/pipermail/pycsw-devel/2013-March/000179.html>`_

**2013-02-21** - `pycsw on OSGeo-Live 6.5 <http://lists.osgeo.org/pipermail/discuss/2013-February/011394.html>`_

**2013-01-14** -  `pycsw Receives OGC Compliance Certification and Reference Implementation Status <http://lists.osgeo.org/pipermail/pycsw-devel/2013-January/000161.html>`_

**2012-09-10** - `pycsw 1.4.0 released <http://lists.osgeo.org/pipermail/pycsw-devel/2012-September/000130.html>`_

**2012-08-21** - `pycsw on OSGeo-Live 6.0 <http://lists.osgeo.org/pipermail/discuss/2012-August/010844.html>`_

**2012-04-08** - `pycsw 1.2.0 released <http://lists.osgeo.org/pipermail/pycsw-devel/2012-April/000088.html>`_

**2012-02-28** - `pycsw on OSGeo-Live 5.5 <http://lists.osgeo.org/pipermail/discuss/2012-February/010151.html>`_

**2012-01-28** - `project updates <http://lists.osgeo.org/pipermail/pycsw-devel/2012-January/000059.html>`_

**2011-06-29** - `pycsw 1.0.0 released <http://lists.osgeo.org/pipermail/pycsw-devel/2011-June/000046.html>`_

**2011-04-20** - `pycsw 0.1.0 released <http://lists.osgeo.org/pipermail/pycsw-devel/2011-April/000025.html>`_
