**2011-06-29 - pycsw 1.0.0 released**

pycsw 1.0.0 has been released. `Release announcement <https://sourceforge.net/mailarchive/forum.php?thread_name=4E0B53AE.7040700%40gmail.com&forum_name=pycsw-devel>`_.

**2011-04-20 - pycsw 0.1.0 released**

pycsw 0.1.0 has been released. `Release announcement <https://sourceforge.net/mailarchive/forum.php?thread_name=4DAE1BEC.2040006%40gmail.com&forum_name=pycsw-devel>`_.
