**2012-04-08** - `pycsw 1.2.0 released <http://lists.osgeo.org/pipermail/pycsw-devel/2012-April/000088.html>`_

**2012-02-28** - `pycsw on OSGeo-Live 5.5 <http://lists.osgeo.org/pipermail/discuss/2012-February/010151.html>`_

**2012-01-28** - `project updates <http://lists.osgeo.org/pipermail/pycsw-devel/2012-January/000059.html>`_

**2011-06-29** - `pycsw 1.0.0 released <http://lists.osgeo.org/pipermail/pycsw-devel/2011-June/000046.html>`_

**2011-04-20** - `pycsw 0.1.0 released <http://lists.osgeo.org/pipermail/pycsw-devel/2011-April/000025.html>`_
