{{- if .Values.nginx.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $chartName := include "pycsw.name" . -}}
{{- $cloudProviderDockerRegistryUrl := include "pycsw.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "pycsw.cloudProviderImagePullSecretName" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-nginx-deployment
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ $releaseName }}-{{ $chartName }}
    component: nginx-deployment
    environment: {{ .Values.environment }}
    release: {{ $releaseName }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: {{ $releaseName }}-{{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-nginx
  template:
    metadata:
      labels:
        app: {{ $releaseName }}-{{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-nginx
      # Autodiscover annotations should be here
      # https://github.com/elastic/beats/issues/7914
      annotations:
        co.elastic.logs/enabled: 'true'
        co.elastic.logs/module: 'nginx'
        co.elastic.logs/fileset.stdout: 'access'
        co.elastic.logs/fileset.stderr: 'error'
        {{- if .Values.resetOnConfigChange }}
        checksum/nginx-configmap: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
        checksum/envoy-configmap: {{ include (print $.Template.BasePath "/envoy-configmap.yaml") . | sha256sum }}
        {{- end }}
    spec:
    {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
    {{- end }}
      volumes:
        {{- if .Values.authentication.opa.enabled }}
        - name: opa-policy
          secret:
            secretName: {{ $releaseName }}-opa
        - name: proxy-config
          configMap:
            name: {{ $releaseName }}-{{ $chartName }}-envoy-configmap
        - name: jwt-public-keys
          secret:
            secretName: {{ .Values.authentication.jwtPublicKeySecretName }}
        {{- end }}
        - name: jwt-js
          configMap:
            name: {{ $releaseName }}-{{ $chartName }}-nginx-configmap
            items:
            - key: jwt.js
              path: jwt.js
        - name: log-format
          configMap:
            name: {{ $releaseName }}-{{ $chartName }}-nginx-configmap
            items:
            - key: log_format.conf
              path: log_format.conf
        - name: nginx-custom-conf
          configMap:
            name: {{ $releaseName }}-{{ $chartName }}-nginx-configmap
            items:
            - key: default.conf
              path: default.conf
        - name: nginx-root-conf
          configMap:
            name: {{ $releaseName }}-{{ $chartName }}-nginx-configmap
            items:
            - key: nginx.conf
              path: nginx.conf
        {{- if .Values.logsFilebeat.enabled }}
        - name: logs
          emptyDir: {}
        - name: config
          configMap:
            name: filebeat-config
        {{- end }}
      containers:
        ## Nginx Deployment
        - name: {{ $releaseName }}-nginx
          {{- with .Values.nginx.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ .tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
          - name: jwt-js
            mountPath: /etc/nginx/jwt.js
            subPath: jwt.js
            readOnly: true
          - name: log-format
            mountPath: /etc/nginx/log_format.conf
            subPath: log_format.conf
            readOnly: true
          - name: nginx-custom-conf
            mountPath: /etc/nginx/conf.d
            readOnly: true
          - name: nginx-root-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
          {{- if .Values.logsFilebeat.enabled }}
          - name: logs
            mountPath: {{ .Values.logsFilebeat.nginxMountPath }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.env.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: {{ .Values.env.port }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: {{ .Values.env.port }}
          {{- if .Values.nginx.resources.enabled }}
          resources:
            {{- toYaml .Values.nginx.resources.value | nindent 12 }}
          {{- end }}
        {{- if .Values.authentication.opa.enabled }}
        - name: envoy
          image: {{ .Values.envoy.image }}:{{ .Values.envoy.imageTag }}
          volumeMounts:
          - name: proxy-config
            mountPath: /config
            readOnly: true
          - name: jwt-public-keys
            mountPath: /keys/mapColonies.jwks
            subPath: mapColonies.jwks
            readOnly: true
          args:
          - "envoy"
          - "--config-path"
          - "/config/envoy.yaml"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          {{- if .Values.envoy.resources.enabled }}
          resources:
            {{- toYaml .Values.envoy.resources.value | nindent 12 }}
          {{- end }}
        - name: opa
          image: {{ .Values.opa.image }}:{{ .Values.opa.imageTag }}
          volumeMounts:
          - name: opa-policy
            mountPath: /policy
            readOnly: true
          args:
          - "run"
          - "--server"
          - "--addr=0.0.0.0:8181"
          - "--diagnostic-addr=0.0.0.0:8282"
          - "--set=plugins.envoy_ext_authz_grpc.add=:{{ .Values.opa.imageTag }}"
          - "--set=plugins.envoy_ext_authz_grpc.path=envoy/authz/allow"
          {{- if .Values.opa.enableLogging }}
          - "--set=decision_logs.console=true"
          {{- end }}
          - "/policy/policy.rego"
          {{- if .Values.opa.resources.enabled }}
          resources:
            {{- toYaml .Values.opa.resources.value | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .Values.logsFilebeat.enabled }}
        - name: filebeat
          image: {{ .Values.logsFilebeat.filebeatImage }}
          args: [ "-c", "/etc/filebeat.yml", "-e" ]
          volumeMounts:
            - name: logs
              mountPath: {{ .Values.logsFilebeat.nginxMountPath }}
            - name: config
              mountPath: /etc/filebeat.yml
              subPath: filebeat.yml
        {{- end }}
{{- end }}
