
# pycsw custom uwsgi settings injected into root location
uwsgi_pass {{ include "service.fullname" . }}:{{ .Values.servicePort }}; 
include uwsgi_params;
uwsgi_hide_header Set-Cookie;
uwsgi_param HTTP_Cookie "";
