apiVersion: v2
name: pycsw
description: A Helm chart for pycsw service
type: application
version: 6.5.0
appVersion: 6.5.0
dependencies:
  - name: nginx
    version: 2.1.6
    repository: oci://acrarolibotnonprod.azurecr.io/helm/common
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
