apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.global.namespace }}
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.db.volume_name }}
  name: {{ .Values.db.volume_name }}
spec:
  {{ if .Values.db.volume_storage_type }}
  storageClassName: {{ .Values.db.volume_storage_type }}
  {{ end }}
  accessModes:
  - {{ .Values.db.volume_access_modes }}
  resources:
    requests:
      storage: {{ .Values.db.volume_size }}
status: {}
