apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.global.namespace }}
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.db.pgdata_volume_name }}
  name: {{ .Values.db.pgdata_volume_name }}
spec:
  storageClassName: {{ .Values.db.pgdata_volume_storage_type }}
  accessModes:
  - {{ .Values.db.pgdata_volume_access_modes }}
  resources:
    requests:
      storage: {{ .Values.db.pgdata_volume_size }}
status: {}
