apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.namespace }}
  labels:
    io.kompose.service: {{ .Values.db.name }}
  name: {{ .Values.db.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.db.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.db.name }}
    spec:
      containers:
      - env:
        - name: PGDATA
          value: {{ .Values.db.pgdata_volume_path }}
        - name: POSTGRES_DB
          value: {{ .Values.db.database }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.db.pass }}
        - name: POSTGRES_USER
          value: {{ .Values.db.user }}
        image: {{ .Values.db.image }}
        name: {{ .Values.db.user }}
        ports:
        - containerPort: {{ .Values.db.port }}
        resources: {}
        volumeMounts:
        - mountPath: {{ .Values.db.pgdata_volume_path }}
          name: {{ .Values.db.pgdata_volume_name }}
      restartPolicy: Always
      volumes:
      - name: {{ .Values.db.pgdata_volume_name }}
        persistentVolumeClaim:
          claimName: {{ .Values.db.pgdata_volume_name }}
status: {}
