name: build ⚙️

on: 
  push:
    branches:
      - master
      - 2.6
    paths-ignore:
      - '**.md'  
  pull_request:
    branches:
      - master
      - 2.6
    paths-ignore:
      - '**.md'  
  release:
    types:
      - released

jobs:
  main:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - python-version: "3.12"
            toxenv: "py310-sqlite"
    env:
        TOXENV: ${{ matrix.toxenv }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v5
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements 📦
      run: |
        sudo apt install -y libgeos-dev libpq-dev libxml2-dev libxslt1-dev libz-dev libexpat1
        pip3 install -r requirements.txt
        pip3 install -r requirements-standalone.txt
        pip3 install -r requirements-dev.txt
        pip3 install tox
        echo "TOXENV => $TOXENV"
    - name: run unit tests ⚙️
      run: tox -- --exitfirst -m unit
    - name: run integration tests ⚙️
      run: tox -- --exitfirst -m functional -k 'not harvesting'
    - name: build docs 🏗️
      run: cd docs && make html
